/**
 * SF Precision Comparison Test
 *
 * Reads reference state vectors generated by Strawberry Fields TF backend
 * (via experiments/python/generate_sf_reference.py) and compares them against
 * our GPU implementation's output for the same gate sequences.
 *
 * Run generate_sf_reference.py first to create reference data, then run this test.
 * Set SF_REFERENCE_DIR env var to point to the reference data directory.
 */

#include <gtest/gtest.h>
#include <vector>
#include <complex>
#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <iostream>
#include <map>
#include <algorithm>
#include "quantum_circuit.h"
#include "reference_gates.h"

namespace {

// ---------------------------------------------------------------------------
// Simple key=value header file parser (no JSON dependency)
// ---------------------------------------------------------------------------

struct SFReferenceData {
    std::string name;
    std::string gate;
    int num_modes = 1;
    int cutoff = 16;
    std::map<std::string, std::string> params;
    std::vector<std::complex<double>> state_vector;
    bool valid = false;

    double param_double(const std::string& key, double def = 0.0) const {
        auto it = params.find(key);
        if (it == params.end()) return def;
        try { return std::stod(it->second); }
        catch (...) { return def; }
    }
    int param_int(const std::string& key, int def = 0) const {
        auto it = params.find(key);
        if (it == params.end()) return def;
        try { return std::stoi(it->second); }
        catch (...) { return def; }
    }
    std::string param_str(const std::string& key, const std::string& def = "") const {
        auto it = params.find(key);
        return (it != params.end()) ? it->second : def;
    }
};

SFReferenceData load_sf_reference(const std::string& filepath) {
    SFReferenceData data;
    std::ifstream in(filepath);
    if (!in.is_open()) return data;

    // Read header lines starting with #
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) break;  // blank line = end of header
        if (line[0] != '#') {
            // Not a header line; put it back conceptually
            // by seeking. Instead, parse it as the count.
            std::istringstream iss(line);
            int count;
            if (iss >> count) {
                data.state_vector.resize(count);
                for (int i = 0; i < count; ++i) {
                    double re, im;
                    in >> re >> im;
                    data.state_vector[i] = {re, im};
                }
            }
            break;
        }
        // Parse "# key=value"
        size_t eq = line.find('=');
        if (eq != std::string::npos && eq > 2) {
            std::string key = line.substr(2, eq - 2);  // skip "# "
            std::string val = line.substr(eq + 1);
            data.params[key] = val;
        }
    }

    // If we hit blank line, next line is count
    if (data.state_vector.empty()) {
        int count = 0;
        in >> count;
        if (count > 0) {
            data.state_vector.resize(count);
            for (int i = 0; i < count; ++i) {
                double re, im;
                in >> re >> im;
                data.state_vector[i] = {re, im};
            }
        }
    }

    data.name = data.param_str("name", "unknown");
    data.gate = data.param_str("gate", "unknown");
    data.num_modes = data.param_int("num_modes", 1);
    data.cutoff = data.param_int("cutoff", 16);
    data.valid = !data.state_vector.empty();
    return data;
}

// ---------------------------------------------------------------------------
// Precision metrics
// ---------------------------------------------------------------------------

struct PrecisionMetrics {
    double l2_error = 0.0;
    double max_error = 0.0;
    double fidelity = 0.0;
    double norm_diff = 0.0;
};

PrecisionMetrics compute_metrics(
    const std::vector<std::complex<double>>& ref,
    const std::vector<std::complex<double>>& impl)
{
    PrecisionMetrics m;
    if (ref.size() != impl.size()) { m.l2_error = 1e9; return m; }

    double l2_sq = 0.0, ref_norm_sq = 0.0, impl_norm_sq = 0.0;
    std::complex<double> overlap(0.0, 0.0);

    for (size_t i = 0; i < ref.size(); ++i) {
        auto diff = ref[i] - impl[i];
        l2_sq += std::norm(diff);
        m.max_error = std::max(m.max_error, std::abs(diff));
        ref_norm_sq += std::norm(ref[i]);
        impl_norm_sq += std::norm(impl[i]);
        overlap += std::conj(ref[i]) * impl[i];
    }

    m.l2_error = std::sqrt(l2_sq);
    m.fidelity = std::norm(overlap) / (ref_norm_sq * impl_norm_sq + 1e-30);
    m.norm_diff = std::abs(std::sqrt(ref_norm_sq) - std::sqrt(impl_norm_sq));
    return m;
}

// ---------------------------------------------------------------------------
// Extract full state vector from QuantumCircuit
// ---------------------------------------------------------------------------

std::vector<std::complex<double>> extract_state_vector_1mode(
    QuantumCircuit& circuit, int cutoff)
{
    std::vector<std::complex<double>> sv(cutoff);
    for (int n = 0; n < cutoff; ++n) {
        std::vector<std::complex<double>> basis(cutoff, {0.0, 0.0});
        basis[n] = {1.0, 0.0};
        sv[n] = circuit.get_amplitude({0}, {basis});
    }
    return sv;
}

std::vector<std::complex<double>> extract_state_vector_2mode(
    QuantumCircuit& circuit, int cutoff)
{
    std::vector<std::complex<double>> sv(cutoff * cutoff);
    for (int n0 = 0; n0 < cutoff; ++n0) {
        std::vector<std::complex<double>> b0(cutoff, {0.0, 0.0});
        b0[n0] = {1.0, 0.0};
        for (int n1 = 0; n1 < cutoff; ++n1) {
            std::vector<std::complex<double>> b1(cutoff, {0.0, 0.0});
            b1[n1] = {1.0, 0.0};
            sv[n0 * cutoff + n1] = circuit.get_amplitude({0}, {b0, b1});
        }
    }
    return sv;
}

// ---------------------------------------------------------------------------
// Build circuit from reference data params
// ---------------------------------------------------------------------------

bool build_circuit_from_ref(QuantumCircuit& circuit, const SFReferenceData& ref) {
    const std::string& gate = ref.gate;

    if (gate == "DISPLACEMENT") {
        double r = ref.param_double("r");
        double phi = ref.param_double("phi");
        circuit.add_gate(Gates::Displacement(0, std::polar(r, phi)));
        return true;
    }
    if (gate == "SQUEEZING") {
        double r = ref.param_double("r");
        double phi = ref.param_double("phi");
        circuit.add_gate(Gates::Squeezing(0, std::polar(r, phi)));
        return true;
    }
    if (gate == "PHASE_ROTATION") {
        circuit.add_gate(Gates::PhaseRotation(0, ref.param_double("theta")));
        return true;
    }
    if (gate == "KERR_GATE") {
        circuit.add_gate(Gates::KerrGate(0, ref.param_double("kappa")));
        return true;
    }
    if (gate == "BEAM_SPLITTER") {
        circuit.add_gate(Gates::Displacement(0, {0.5, 0.0}));
        circuit.add_gate(Gates::BeamSplitter(0, 1,
            ref.param_double("theta"), ref.param_double("phi")));
        return true;
    }
    if (gate == "CROSS_KERR_GATE") {
        circuit.add_gate(Gates::Displacement(0, {0.3, 0.0}));
        circuit.add_gate(Gates::Displacement(1, {0.4, 0.0}));
        circuit.add_gate(Gates::CrossKerr(0, 1, ref.param_double("kappa")));
        return true;
    }
    if (gate == "COMPOSED_D_K") {
        circuit.add_gate(Gates::Displacement(0, {ref.param_double("d_r"), 0.0}));
        circuit.add_gate(Gates::KerrGate(0, ref.param_double("kappa")));
        return true;
    }
    if (gate == "COMPOSED_S_D") {
        circuit.add_gate(Gates::Squeezing(0, {ref.param_double("s_r"), 0.0}));
        circuit.add_gate(Gates::Displacement(0, {ref.param_double("d_r"), 0.0}));
        return true;
    }
    if (gate == "BEAM_SPLITTER_COMPOSED") {
        circuit.add_gate(Gates::Squeezing(0, {ref.param_double("s_r"), 0.0}));
        circuit.add_gate(Gates::Displacement(1, {ref.param_double("d_r"), 0.0}));
        circuit.add_gate(Gates::BeamSplitter(0, 1,
            ref.param_double("theta"), ref.param_double("phi")));
        return true;
    }
    std::cerr << "Unknown gate type: " << gate << "\n";
    return false;
}

// ---------------------------------------------------------------------------
// Find reference data directory
// ---------------------------------------------------------------------------

std::string find_reference_dir() {
    const char* env_dir = std::getenv("SF_REFERENCE_DIR");
    if (env_dir) {
        std::ifstream probe(std::string(env_dir) + "/.");
        if (probe.good()) return env_dir;
    }
    // Search relative paths
    for (const char* p : {"experiments/sf_reference_data",
                          "../experiments/sf_reference_data",
                          "../../experiments/sf_reference_data"}) {
        std::ifstream probe(std::string(p) + "/.");
        // Try to list directory by opening a known file pattern
        // A simpler check: try to open manifest
        for (int c : {16, 8, 32}) {
            std::string mpath = std::string(p) + "/manifest_c" + std::to_string(c) + ".json";
            std::ifstream mf(mpath);
            if (mf.good()) return p;
        }
    }
    return "";
}

// Find reference file by case name
std::string find_reference_file(const std::string& dir, const std::string& case_name) {
    for (int c : {16, 8, 32}) {
        std::string path = dir + "/sf_ref_" + case_name + "_c" + std::to_string(c) + ".txt";
        std::ifstream f(path);
        if (f.good()) return path;
    }
    return "";
}

}  // namespace

// ===========================================================================
// Test fixture
// ===========================================================================

class SFPrecisionTest : public ::testing::Test {
protected:
    std::string ref_dir_;

    void SetUp() override {
        ref_dir_ = find_reference_dir();
    }

    void run_comparison(const std::string& case_name,
                        double l2_tol, double fid_tol)
    {
        if (ref_dir_.empty()) {
            GTEST_SKIP() << "No SF reference data. Run generate_sf_reference.py first.";
        }

        std::string filepath = find_reference_file(ref_dir_, case_name);
        if (filepath.empty()) {
            GTEST_SKIP() << "Reference file not found for: " << case_name;
        }

        auto ref = load_sf_reference(filepath);
        ASSERT_TRUE(ref.valid) << "Failed to load: " << filepath;

        // Build and run our circuit
        QuantumCircuit circuit(1, ref.num_modes, ref.cutoff, 1024);
        ASSERT_TRUE(build_circuit_from_ref(circuit, ref))
            << "Cannot build circuit for: " << case_name;
        circuit.build();
        circuit.execute();

        // Extract state vector
        std::vector<std::complex<double>> our_sv;
        if (ref.num_modes == 1)
            our_sv = extract_state_vector_1mode(circuit, ref.cutoff);
        else
            our_sv = extract_state_vector_2mode(circuit, ref.cutoff);

        auto m = compute_metrics(ref.state_vector, our_sv);
        std::cout << "  [SF] " << case_name
                  << ": L2=" << m.l2_error
                  << " MaxErr=" << m.max_error
                  << " Fidelity=" << m.fidelity
                  << " NormDiff=" << m.norm_diff << "\n";

        EXPECT_LT(m.l2_error, l2_tol) << case_name << " L2 too large";
        EXPECT_GT(m.fidelity, 1.0 - fid_tol) << case_name << " fidelity too low";
    }
};

// ===========================================================================
// Gate-level precision tests against Strawberry Fields
// ===========================================================================

// Displacement
TEST_F(SFPrecisionTest, Displacement_r0p3) {
    run_comparison("displacement_r0.3_phi0.00", 1e-4, 1e-6);
}
TEST_F(SFPrecisionTest, Displacement_r0p5) {
    run_comparison("displacement_r0.5_phi0.00", 1e-4, 1e-6);
}
TEST_F(SFPrecisionTest, Displacement_r1p0) {
    run_comparison("displacement_r1.0_phi0.00", 1e-3, 1e-4);
}
TEST_F(SFPrecisionTest, Displacement_complex) {
    run_comparison("displacement_r0.3_phi0.50", 1e-4, 1e-6);
}

// Squeezing
TEST_F(SFPrecisionTest, Squeezing_r0p2) {
    run_comparison("squeezing_r0.2_phi0.00", 1e-4, 1e-6);
}
TEST_F(SFPrecisionTest, Squeezing_r0p5) {
    run_comparison("squeezing_r0.5_phi0.00", 1e-3, 1e-5);
}
TEST_F(SFPrecisionTest, Squeezing_r0p8) {
    run_comparison("squeezing_r0.8_phi0.00", 1e-2, 1e-3);
}
TEST_F(SFPrecisionTest, Squeezing_complex) {
    run_comparison("squeezing_r0.3_phi0.70", 1e-3, 1e-5);
}

// Phase Rotation
TEST_F(SFPrecisionTest, PhaseRotation_0p3) {
    run_comparison("phase_rotation_theta0.3000", 1e-6, 1e-10);
}
TEST_F(SFPrecisionTest, PhaseRotation_pi) {
    run_comparison("phase_rotation_theta3.1416", 1e-6, 1e-10);
}

// Kerr
TEST_F(SFPrecisionTest, Kerr_0p1) {
    run_comparison("kerr_kappa0.1", 1e-6, 1e-10);
}
TEST_F(SFPrecisionTest, Kerr_1p0) {
    run_comparison("kerr_kappa1.0", 1e-6, 1e-10);
}

// Beam Splitter (2-mode)
TEST_F(SFPrecisionTest, BeamSplitter_0p3) {
    run_comparison("beamsplitter_theta0.3000_phi0.00", 1e-3, 1e-4);
}
TEST_F(SFPrecisionTest, BeamSplitter_piOver4) {
    run_comparison("beamsplitter_theta0.7854_phi0.00", 1e-3, 1e-4);
}

// Cross-Kerr (2-mode)
TEST_F(SFPrecisionTest, CrossKerr_0p1) {
    run_comparison("cross_kerr_kappa0.1", 1e-3, 1e-4);
}

// Composed sequences
TEST_F(SFPrecisionTest, DisplaceThenKerr) {
    run_comparison("displace_then_kerr_r0.5_k0.3", 1e-3, 1e-4);
}
TEST_F(SFPrecisionTest, SqueezeThenDisplace) {
    run_comparison("squeeze_then_displace_sr0.3_dr0.5", 1e-3, 1e-4);
}
TEST_F(SFPrecisionTest, BSOnSqueezedDisplaced) {
    run_comparison("bs_on_squeezed_displaced", 1e-2, 1e-3);
}
