#!/usr/bin/env python3
"""
生成符合 BQSim 要求的 QASM 文件
"""

import json
import os
import sys
import math
import random
import concurrent.futures
import multiprocessing

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'qasm')
ALLOWED_CUTOFFS = [4, 8, 16, 32]
MAX_WORKERS = 4


def create_vqe_circuit_qasm(name, num_qubits, num_modes, cutoff, layers=2):
    """生成 VQE 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成随机参数
    random.seed(42)
    params = []
    for i in range(layers):
        for qm in range(num_modes):
            params.append(random.uniform(0, 3))
            params.append(random.uniform(0, math.pi))
        for q in range(num_qubits):
            params.append(random.uniform(0, math.pi))
            params.append(random.uniform(0, math.pi))
    
    # 生成电路操作
    param_idx = 0
    for d in range(layers):
        # 添加位移门
        for qm in range(num_modes):
            beta_mag = params[param_idx]
            beta_arg = params[param_idx + 1]
            param_idx += 2
            # 使用 U1 门模拟位移操作
            qasm_lines.append(f'u1({beta_mag}) qm{qm}[0];')
        
        # 添加量子比特旋转
        for q in range(num_qubits):
            theta = params[param_idx]
            phi = params[param_idx + 1]
            param_idx += 2
            qasm_lines.append(f'rx({theta}) q[{q}];')
            qasm_lines.append(f'rz({phi}) q[{q}];')
        
        # 添加 beamsplitter 操作（使用 CNOT 门模拟）
        for qm in range(num_modes - 1):
            qasm_lines.append(f'cx qm{qm}[0],qm{qm+1}[0];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_jch_circuit_qasm(name, num_qubits, num_modes, cutoff, timesteps=5, J=0.1, omega_r=1.0, omega_q=1.0, g=0.1, tau=0.1):
    """生成 JCH 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    for t in range(timesteps):
        # 谐振子旋转
        for i in range(num_modes):
            angle = omega_r * tau
            qasm_lines.append(f'rx({angle}) qm{i}[0];')
        
        # 量子比特旋转
        for i in range(num_qubits):
            angle = omega_q * tau / 2.0
            qasm_lines.append(f'rz({angle}) q[{i}];')
        
        # 耦合操作
        for i in range(min(num_modes - 1, num_qubits)):
            angle = g * tau
            qasm_lines.append(f'cx qm{i}[0],qm{i+1}[0];')
        
        # 谐振子间耦合
        for i in range(num_modes - 1):
            angle = J * tau
            qasm_lines.append(f'cx qm{i}[0],qm{i+1}[0];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_cat_state_circuit_qasm(name, num_qubits, num_modes, cutoff, alpha=1.0):
    """生成 Cat 态电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    
    # 位移操作
    displacement_param = alpha / math.sqrt(2)
    qasm_lines.append(f'u({displacement_param},0,0) qm0[0];')
    qasm_lines.append('cx q[0],qm0[0];')
    qasm_lines.append('')
    
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    
    qasm_lines.append('p(pi) q[0];')
    qasm_lines.append('p(pi) q[0];')
    qasm_lines.append('p(pi) q[0];')
    qasm_lines.append('')
    
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    
    # 另一个位移操作
    displacement_param2 = math.pi / (8 * alpha * math.sqrt(2))
    qasm_lines.append(f'u({displacement_param2},pi/2,0) qm0[0];')
    qasm_lines.append('cx q[0],qm0[0];')
    qasm_lines.append('')
    
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    qasm_lines.append('p(pi/2) q[0];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_gkp_state_circuit_qasm(name, num_qubits, num_modes, cutoff, N_rounds=9, r=0.222):
    """生成 GKP 态电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    alpha = math.sqrt(math.pi)
    
    # 压缩操作
    qasm_lines.append(f'u({r},0,0) qm0[0];')
    qasm_lines.append('')
    
    for i in range(1, N_rounds):
        qasm_lines.append('h q[0];')
        qasm_lines.append('')
        
        # 位移操作
        displacement_param = alpha / math.sqrt(2)
        qasm_lines.append(f'u({displacement_param},0,0) qm0[0];')
        qasm_lines.append('cx q[0],qm0[0];')
        qasm_lines.append('')
        
        qasm_lines.append('h q[0];')
        qasm_lines.append('p(pi) q[0];')
        qasm_lines.append('h q[0];')
        qasm_lines.append('')
        
        # 另一个位移操作
        displacement_param2 = math.pi / (8 * alpha * math.sqrt(2))
        qasm_lines.append(f'u({displacement_param2},pi/2,0) qm0[0];')
        qasm_lines.append('cx q[0],qm0[0];')
        qasm_lines.append('')
        
        qasm_lines.append('h q[0];')
        qasm_lines.append('p(pi/2) q[0];')
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_qaoa_circuit_qasm(name, num_qubits, num_modes, cutoff, layers=2, s=0.5, a=1.0):
    """生成 QAOA 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    for qm in range(num_modes):
        qasm_lines.append(f'u({s},0,0) qm{qm}[0];')
    qasm_lines.append('')
    
    params = [2 * math.pi * (i + 1) / (2 * layers) for i in range(2 * layers)]
    
    for i in range(layers):
        gamma = params[i]
        eta = params[layers + i]
        
        for qm in range(num_modes):
            qasm_lines.append(f'u({a * gamma},0,0) qm{qm}[0];')
        qasm_lines.append('')
        
        for qm in range(num_modes):
            qasm_lines.append(f'u({eta},0,0) qm{qm}[0];')
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_qft_circuit_qasm(name, num_qubits, num_modes, cutoff, n=2, a=1, append=1, delta=0.1):
    """生成 QFT 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    for qm in range(num_modes):
        qasm_lines.append(f'rx(pi/4.0) qm{qm}[0];')
    qasm_lines.append('')
    
    qasm_lines.append('u(0.29,0,0) qm0[0];')
    qasm_lines.append('')
    
    delta_prime = (2 * math.pi) / (math.pow(2, n + a + append) * delta)
    qasm_lines.append(f'u({delta / 2},0,0) qm0[0];')
    qasm_lines.append('rx(pi/2.0) qm0[0];')
    qasm_lines.append(f'u({-delta_prime / 2},0,0) qm0[0];')
    qasm_lines.append('')
    
    for qm in range(num_modes):
        qasm_lines.append(f'rx(pi/4.0) qm{qm}[0];')
    qasm_lines.append('')
    
    qasm_lines.append('u(0.29,0,0) qm0[0];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_shors_circuit_qasm(name, num_qubits, num_modes, cutoff, N=15, m=5, R=10, a=2, delta=1.0):
    """生成 Shor 算法电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    r = 0.222
    
    qasm_lines.append(f'u({r},0,0) qm0[0];')
    qasm_lines.append(f'u({r},0,0) qm1[0];')
    qasm_lines.append('')
    
    qasm_lines.append(f'u({-math.log(delta)},0,0) qm2[0];')
    qasm_lines.append('')
    
    for i in range(R):
        qasm_lines.append('u(1.0,0,0) qm0[0];')
    qasm_lines.append('')
    
    for i in range(N):
        qasm_lines.append('u(1.0,0,0) qm1[0];')
    qasm_lines.append('')
    
    for i in range(m):
        qasm_lines.append('cx qm1[0],qm2[0];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_state_transfer_CVtoDV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val=0.29):
    """生成 CV 到 DV 状态转移电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    for j in range(1, num_qubits + 1):
        for q_idx in range(num_qubits):
            qasm_lines.append(f'rx(pi/4) q[{q_idx}];')
        qasm_lines.append('')
        
        for qm in range(num_modes):
            qasm_lines.append(f'u({lambda_val},0,0) qm{qm}[0];')
        qasm_lines.append('')
        
        for q_idx in range(num_qubits):
            qasm_lines.append(f'rz(pi/4) q[{q_idx}];')
        qasm_lines.append('')
        
        for qm in range(num_modes):
            qasm_lines.append(f'u({lambda_val},0,0) qm{qm}[0];')
        qasm_lines.append('')
    
    for i in range(num_qubits):
        qasm_lines.append(f'h q[{i}];')
        if i == num_qubits - 1:
            qasm_lines.append(f'rx(pi) q[{i}];')
            qasm_lines.append(f'p(pi) q[{i}];')
        elif i == 0:
            qasm_lines.append(f'p(pi) q[{i}];')
        else:
            qasm_lines.append(f'rx(pi) q[{i}];')
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_state_transfer_DVtoCV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val=0.29):
    """生成 DV 到 CV 状态转移电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    for i in range(num_qubits):
        if i == num_qubits - 1:
            qasm_lines.append(f'p(pi) q[{i}];')
            qasm_lines.append(f'rx(pi) q[{i}];')
            qasm_lines.append(f'h q[{i}];')
        elif i == 0:
            qasm_lines.append(f'p(pi) q[{i}];')
            qasm_lines.append(f'h q[{i}];')
        else:
            qasm_lines.append(f'rx(pi) q[{i}];')
            qasm_lines.append(f'h q[{i}];')
        qasm_lines.append('')
    
    for j in range(num_qubits, 0, -1):
        for qm in range(num_modes):
            qasm_lines.append(f'u({-lambda_val},0,0) qm{qm}[0];')
        qasm_lines.append('')
        
        for q_idx in range(num_qubits):
            qasm_lines.append(f'rz(-pi/4) q[{q_idx}];')
        qasm_lines.append('')
        
        for qm in range(num_modes):
            qasm_lines.append(f'u({-lambda_val},0,0) qm{qm}[0];')
        qasm_lines.append('')
        
        for q_idx in range(num_qubits):
            qasm_lines.append(f'rx(-pi/4) q[{q_idx}];')
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def write_qasm_file(qasm_code, filename):
    """将 QASM 代码写入文件"""
    try:
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        with open(filename, 'w') as f:
            f.write(qasm_code)
        return True
    except Exception as e:
        print(f"Error writing QASM file: {e}")
        return False


def process_case(case):
    """处理单个 case，返回 (status, output_name, file_size_or_error)"""
    name = case['name']
    workload = case['workload']
    cutoff = case.get('cutoff', 4)
    num_qubits = case.get('num_qubits', 1)
    num_modes = case.get('num_modes', 1)
    
    output_name = f"{name}.qasm"
    output_path = os.path.join(OUTPUT_DIR, output_name)
    
    if os.path.exists(output_path):
        file_size = os.path.getsize(output_path)
        return ('skip', output_name, file_size)
    

    
    try:
        if workload == 'vqe_circuit':
            layers = case.get('layers', 2)
            qasm_code = create_vqe_circuit_qasm(name, num_qubits, num_modes, cutoff, layers)
        elif workload == 'jch_simulation_circuit':
            timesteps = case.get('timesteps', 5)
            qasm_code = create_jch_circuit_qasm(name, num_qubits, num_modes, cutoff, timesteps)
        elif workload == 'cat_state_circuit':
            alpha = case.get('alpha', 1.0)
            qasm_code = create_cat_state_circuit_qasm(name, num_qubits, num_modes, cutoff, alpha)
        elif workload == 'gkp_state_circuit':
            N_rounds = case.get('N_rounds', 9)
            r = case.get('r', 0.222)
            qasm_code = create_gkp_state_circuit_qasm(name, num_qubits, num_modes, cutoff, N_rounds, r)
        elif workload == 'qaoa_circuit':
            layers = case.get('layers', 2)
            s = case.get('s', 0.5)
            a = case.get('a', 1.0)
            qasm_code = create_qaoa_circuit_qasm(name, num_qubits, num_modes, cutoff, layers, s, a)
        elif workload == 'qft_circuit':
            n = case.get('n', 2)
            a = case.get('a', 1)
            append = case.get('append', 1)
            delta = case.get('delta', 0.1)
            qasm_code = create_qft_circuit_qasm(name, num_qubits, num_modes, cutoff, n, a, append, delta)
        elif workload == 'shors_circuit':
            N = case.get('N', 15)
            m = case.get('m', 5)
            R = case.get('R', 10)
            a = case.get('a', 2)
            delta = case.get('delta', 1.0)
            qasm_code = create_shors_circuit_qasm(name, num_qubits, num_modes, cutoff, N, m, R, a, delta)
        elif workload == 'state_transfer_CVtoDV_circuit':
            lambda_val = case.get('lambda', 0.29)
            qasm_code = create_state_transfer_CVtoDV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val)
        elif workload == 'state_transfer_DVtoCV_circuit':
            lambda_val = case.get('lambda', 0.29)
            qasm_code = create_state_transfer_DVtoCV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val)
        else:
            return ('unknown', output_name, workload)
        
        result = write_qasm_file(qasm_code, output_path)
        if result:
            file_size = os.path.getsize(output_path)
            return ('ok', output_name, file_size)
        else:
            return ('error', output_name, 'write failed')
            
    except Exception as e:
        return ('error', output_name, str(e))


def main():
    json_path = os.path.join(os.path.dirname(__file__), 'sc26_scaling.json')
    
    if not os.path.exists(json_path):
        print(f"Cannot find sc26_scaling.json: {json_path}")
        return 1
    
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    cases_by_cutoff = {}
    for case in data['cases']:
        cutoff = case.get('cutoff', 4)
        if cutoff not in ALLOWED_CUTOFFS:
            continue
        if cutoff not in cases_by_cutoff:
            cases_by_cutoff[cutoff] = []
        cases_by_cutoff[cutoff].append(case)
    
    sorted_cutoffs = sorted(cases_by_cutoff.keys())
    
    print(f"Found {len(data['cases'])} test cases in sc26_scaling.json")
    print(f"Generating QASM for cutoffs: {sorted_cutoffs}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Using {MAX_WORKERS} parallel workers")
    print("=" * 80)
    
    total_generated = 0
    total_skipped = 0
    errors = []
    
    for cutoff in sorted_cutoffs:
        print(f"\n>>> Processing cutoff = {cutoff}")
        print("-" * 80)
        
        cases = cases_by_cutoff[cutoff]
        
        with concurrent.futures.ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
            future_to_case = {executor.submit(process_case, case): case for case in cases}
            
            for future in concurrent.futures.as_completed(future_to_case):
                status, output_name, info = future.result()
                
                if status == 'skip':
                    print(f"[SKIP] {output_name} (already exists, {info} bytes)")
                    total_skipped += 1
                elif status == 'ok':
                    print(f"[OK] {output_name} ({info} bytes)")
                    total_generated += 1
                elif status == 'unknown':
                    print(f"[SKIP] {output_name} (unknown workload: {info})")
                else:
                    print(f"[ERROR] {output_name}: {info}")
                    errors.append(output_name)
    
    print("\n" + "=" * 80)
    print(f"Total QASM files generated: {total_generated}")
    print(f"Total skipped (already exist): {total_skipped}")
    if errors:
        print(f"Errors ({len(errors)}):")
        for e in errors:
            print(f"  - {e}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
