// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[2];
qreg q[1];

h q[0];

p(0.7071067811865475) qm0[0];
cx q[0],qm0[0];

h q[0];

p(3.141592653589793) q[0];
p(3.141592653589793) q[0];
p(3.141592653589793) q[0];

h q[0];

p(0.2776801836348979) qm0[0];
cx q[0],qm0[0];

h q[0];

p(1.5707963267948966) q[0];
