// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[2];
qreg qm1[2];
qreg qm2[2];
qreg q[1];

p(0.222) qm0[0];
p(0.222) qm1[0];
p(0.222) qm0[1];
p(0.222) qm1[1];

p(-0.0) qm2[0];
p(-0.0) qm2[1];

p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];
p(1.0) qm0[0];
p(1.0) qm0[1];

p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];
p(1.0) qm1[0];
p(1.0) qm1[1];

cx qm1[0],qm2[0];
cx qm1[1],qm2[1];
cx qm1[0],qm2[0];
cx qm1[1],qm2[1];
cx qm1[0],qm2[0];
cx qm1[1],qm2[1];
cx qm1[0],qm2[0];
cx qm1[1],qm2[1];
cx qm1[0],qm2[0];
cx qm1[1],qm2[1];
