// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[4];
qreg q[5];

rx(pi/4.0) qm0[0];

u(0.29,0,0) qm0[0];

u(0.05,0,0) qm0[0];
rx(pi/2.0) qm0[0];
u(-0.9817477042468103,0,0) qm0[0];

rx(pi/4.0) qm0[0];

u(0.29,0,0) qm0[0];
