// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[2];
qreg q[4];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];

h q[0];
p(pi) q[0];

h q[1];
rx(pi) q[1];

h q[2];
rx(pi) q[2];

h q[3];
rx(pi) q[3];
p(pi) q[3];

