// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[4];
qreg q[2];

rx(pi/4) q[0];
rx(pi/4) q[1];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];

u(0.29,0,0) qm0[0];

h q[0];
p(pi) q[0];

h q[1];
rx(pi) q[1];
p(pi) q[1];

