// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[3];
qreg q[8];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];

u(0.29,0,0) qm0[0];

h q[0];
p(pi) q[0];

h q[1];
rx(pi) q[1];

h q[2];
rx(pi) q[2];

h q[3];
rx(pi) q[3];

h q[4];
rx(pi) q[4];

h q[5];
rx(pi) q[5];

h q[6];
rx(pi) q[6];

h q[7];
rx(pi) q[7];
p(pi) q[7];

