// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[4];
qreg q[16];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

rx(pi/4) q[0];
rx(pi/4) q[1];
rx(pi/4) q[2];
rx(pi/4) q[3];
rx(pi/4) q[4];
rx(pi/4) q[5];
rx(pi/4) q[6];
rx(pi/4) q[7];
rx(pi/4) q[8];
rx(pi/4) q[9];
rx(pi/4) q[10];
rx(pi/4) q[11];
rx(pi/4) q[12];
rx(pi/4) q[13];
rx(pi/4) q[14];
rx(pi/4) q[15];

u(0.29,0,0) qm0[0];

rz(pi/4) q[0];
rz(pi/4) q[1];
rz(pi/4) q[2];
rz(pi/4) q[3];
rz(pi/4) q[4];
rz(pi/4) q[5];
rz(pi/4) q[6];
rz(pi/4) q[7];
rz(pi/4) q[8];
rz(pi/4) q[9];
rz(pi/4) q[10];
rz(pi/4) q[11];
rz(pi/4) q[12];
rz(pi/4) q[13];
rz(pi/4) q[14];
rz(pi/4) q[15];

u(0.29,0,0) qm0[0];

h q[0];
p(pi) q[0];

h q[1];
rx(pi) q[1];

h q[2];
rx(pi) q[2];

h q[3];
rx(pi) q[3];

h q[4];
rx(pi) q[4];

h q[5];
rx(pi) q[5];

h q[6];
rx(pi) q[6];

h q[7];
rx(pi) q[7];

h q[8];
rx(pi) q[8];

h q[9];
rx(pi) q[9];

h q[10];
rx(pi) q[10];

h q[11];
rx(pi) q[11];

h q[12];
rx(pi) q[12];

h q[13];
rx(pi) q[13];

h q[14];
rx(pi) q[14];

h q[15];
rx(pi) q[15];
p(pi) q[15];

