// Generated by BQSim QASM generator

OPENQASM 2.0;
include "qelib1.inc";

qreg qm0[3];
qreg q[7];

rx(pi/4.0) qm0[0];
rx(pi/4.0) qm0[1];
rx(pi/4.0) qm0[2];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];
u(0.29,0,0) qm0[2];

u(0.05,0,0) qm0[0];
rx(pi/2.0) qm0[0];
u(-0.2454369260617026,0,0) qm0[0];
u(0.05,0,0) qm0[1];
rx(pi/2.0) qm0[1];
u(-0.2454369260617026,0,0) qm0[1];
u(0.05,0,0) qm0[2];
rx(pi/2.0) qm0[2];
u(-0.2454369260617026,0,0) qm0[2];

rx(pi/4.0) qm0[0];
rx(pi/4.0) qm0[1];
rx(pi/4.0) qm0[2];

u(0.29,0,0) qm0[0];
u(0.29,0,0) qm0[1];
u(0.29,0,0) qm0[2];
