#!/usr/bin/env python3
"""
生成符合 BQSim 要求的 QASM 文件
"""

import json
import os
import sys
import math
import random
import concurrent.futures
import multiprocessing

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'qasm')
ALLOWED_CUTOFFS = [4, 8, 16, 32]
MAX_WORKERS = 4


def create_vqe_circuit_qasm(name, num_qubits, num_modes, cutoff, layers=2):
    """生成 VQE 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成随机参数
    random.seed(42)
    params = []
    for i in range(layers):
        for qm in range(num_modes):
            params.append(random.uniform(0, 3))
            params.append(random.uniform(0, math.pi))
        for q in range(num_qubits):
            params.append(random.uniform(0, math.pi))
            params.append(random.uniform(0, math.pi))
    
    # 生成电路操作
    param_idx = 0
    for d in range(layers):
        # 添加位移门（对每个模式的所有量子比特应用）
        for qm in range(num_modes):
            beta_mag = params[param_idx]
            beta_arg = params[param_idx + 1]
            param_idx += 2
            num_qubits_per_mode = math.ceil(math.log2(cutoff))
            # 使用 p 门模拟位移操作（对所有量子比特应用）
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'p({beta_mag}) qm{qm}[{qubit_offset}];')
        
        # 添加量子比特旋转
        for q in range(num_qubits):
            theta = params[param_idx]
            phi = params[param_idx + 1]
            param_idx += 2
            # 使用 rz 和 ry 门
            qasm_lines.append(f'rz({theta}) q[{q}];')
            qasm_lines.append(f'ry({phi}) q[{q}];')
        
        # 添加 beamsplitter 操作（使用 CNOT 门模拟，对所有量子比特应用）
        for qm in range(num_modes - 1):
            num_qubits_per_mode = math.ceil(math.log2(cutoff))
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'cx qm{qm}[{qubit_offset}],qm{qm+1}[{qubit_offset}];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_jch_circuit_qasm(name, num_qubits, num_modes, cutoff, timesteps=5, J=0.1, omega_r=1.0, omega_q=1.0, g=0.1, tau=0.1):
    """生成 JCH 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    for t in range(timesteps):
        # 谐振子旋转（对所有量子比特应用）
        for i in range(num_modes):
            angle = omega_r * tau
            num_qubits_per_mode = math.ceil(math.log2(cutoff))
            # 使用 h 和 rz 门（等价于 rx）
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'h qm{i}[{qubit_offset}];')
                qasm_lines.append(f'rz({angle}) qm{i}[{qubit_offset}];')
                qasm_lines.append(f'h qm{i}[{qubit_offset}];')
        
        # 量子比特旋转
        for i in range(num_qubits):
            angle = omega_q * tau / 2.0
            qasm_lines.append(f'rz({angle}) q[{i}];')
        
        # 耦合操作（对所有量子比特应用）
        for i in range(min(num_modes - 1, num_qubits)):
            angle = g * tau
            num_qubits_per_mode = math.ceil(math.log2(cutoff))
            # 使用 h 和 rz 门（等价于 rx）
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'h qm{i}[{qubit_offset}];')
                qasm_lines.append(f'rz({angle}) qm{i}[{qubit_offset}];')
                qasm_lines.append(f'h qm{i}[{qubit_offset}];')
        
        # 谐振子间耦合（对所有量子比特应用）
        for i in range(num_modes - 1):
            num_qubits_per_mode = math.ceil(math.log2(cutoff))
            # 使用 CNOT 门
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'cx qm{i}[{qubit_offset}],qm{i+1}[{qubit_offset}];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_cat_state_circuit_qasm(name, num_qubits, num_modes, cutoff, alpha=1.0):
    """生成 Cat 态电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    
    # 位移操作 - 使用 p 门，对所有模式的第一个量子比特应用
    displacement_param = alpha / math.sqrt(2)
    num_qubits_per_mode = math.ceil(math.log2(cutoff))
    for qm in range(num_modes):
        qasm_lines.append(f'p({displacement_param}) qm{qm}[0];')
        qasm_lines.append(f'cx q[0],qm{qm}[0];')
    qasm_lines.append('')
    
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    
    qasm_lines.append('p(3.141592653589793) q[0];')  # pi
    qasm_lines.append('p(3.141592653589793) q[0];')  # pi
    qasm_lines.append('p(3.141592653589793) q[0];')  # pi
    qasm_lines.append('')
    
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    
    # 另一个位移操作 - 使用 p 门，只对第一个模式的第一个量子比特应用
    displacement_param2 = math.pi / (8 * alpha * math.sqrt(2))
    qasm_lines.append(f'p({displacement_param2}) qm0[0];')
    qasm_lines.append('cx q[0],qm0[0];')
    qasm_lines.append('')
    
    qasm_lines.append('h q[0];')
    qasm_lines.append('')
    qasm_lines.append('p(1.5707963267948966) q[0];')  # pi/2
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_gkp_state_circuit_qasm(name, num_qubits, num_modes, cutoff, N_rounds=9, r=0.222):
    """生成 GKP 态电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    alpha = math.sqrt(math.pi)
    
    # 压缩操作 - 使用 p 门，对所有模式的第一个量子比特应用
    num_qubits_per_mode = math.ceil(math.log2(cutoff))
    for qm in range(num_modes):
        qasm_lines.append(f'p({r}) qm{qm}[0];')
    qasm_lines.append('')
    
    for i in range(1, N_rounds):
        qasm_lines.append('h q[0];')
        qasm_lines.append('')
        
        # 位移操作 - 使用 p 门，对所有模式的第一个量子比特应用
        displacement_param = alpha / math.sqrt(2)
        for qm in range(num_modes):
            qasm_lines.append(f'p({displacement_param}) qm{qm}[0];')
            qasm_lines.append(f'cx q[0],qm{qm}[0];')
        qasm_lines.append('')
        
        qasm_lines.append('h q[0];')
        qasm_lines.append('p(3.141592653589793) q[0];')  # pi
        qasm_lines.append('h q[0];')
        qasm_lines.append('')
        
        # 另一个位移操作 - 使用 p 门，对所有模式的第一个量子比特应用
        displacement_param2 = math.pi / (8 * alpha * math.sqrt(2))
        for qm in range(num_modes):
            qasm_lines.append(f'p({displacement_param2}) qm{qm}[0];')
            qasm_lines.append(f'cx q[0],qm{qm}[0];')
        qasm_lines.append('')
        
        qasm_lines.append('h q[0];')
        qasm_lines.append('p(1.5707963267948966) q[0];')  # pi/2
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_qaoa_circuit_qasm(name, num_qubits, num_modes, cutoff, layers=2, s=0.5, a=1.0):
    """生成 QAOA 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    num_qubits_per_mode = math.ceil(math.log2(cutoff))
    for qm in range(num_modes):
        # 使用 p 门，对每个模式的所有量子比特应用
        for qubit_offset in range(num_qubits_per_mode):
            qasm_lines.append(f'p({s}) qm{qm}[{qubit_offset}];')
    qasm_lines.append('')
    
    params = [2 * math.pi * (i + 1) / (2 * layers) for i in range(2 * layers)]
    
    for i in range(layers):
        gamma = params[i]
        eta = params[layers + i]
        
        for qm in range(num_modes):
            # 使用 p 门，对每个模式的所有量子比特应用
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'p({a * gamma}) qm{qm}[{qubit_offset}];')
        qasm_lines.append('')
        
        for qm in range(num_modes):
            # 使用 p 门，对每个模式的所有量子比特应用
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'p({eta}) qm{qm}[{qubit_offset}];')
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_qft_circuit_qasm(name, num_qubits, num_modes, cutoff, n=2, a=1, append=1, delta=0.1):
    """生成 QFT 电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作 - 使用具体的数值，对每个模式的所有量子比特应用
    num_qubits_per_mode = math.ceil(math.log2(cutoff))
    for qm in range(num_modes):
        # rx(pi/4.0) 等价于：h -> rz(pi/4.0) -> h
        for qubit_offset in range(num_qubits_per_mode):
            qasm_lines.append(f'h qm{qm}[{qubit_offset}];')
            qasm_lines.append(f'rz(0.7853981633974483) qm{qm}[{qubit_offset}];')  # pi/4
            qasm_lines.append(f'h qm{qm}[{qubit_offset}];')
    qasm_lines.append('')
    
    # 使用具体的数值 - p 门，对第一个模式的所有量子比特应用
    for qubit_offset in range(num_qubits_per_mode):
        qasm_lines.append(f'p(0.39269908169872414) qm0[{qubit_offset}];')  # pi/8
    qasm_lines.append('')
    
    # 简化参数计算 - p 门，对第一个模式的所有量子比特应用
    for qubit_offset in range(num_qubits_per_mode):
        qasm_lines.append(f'p(0.15707963267948966) qm0[{qubit_offset}];')  # pi/20
        # rx(pi/2.0) 等价于：h -> rz(pi/2.0) -> h
        qasm_lines.append(f'h qm0[{qubit_offset}];')
        qasm_lines.append(f'rz(1.5707963267948966) qm0[{qubit_offset}];')  # pi/2
        qasm_lines.append(f'h qm0[{qubit_offset}];')
        qasm_lines.append(f'p(-1.5707963267948966) qm0[{qubit_offset}];')  # -pi/2
    qasm_lines.append('')
    
    for qm in range(num_modes):
        # rx(pi/4.0) 等价于：h -> rz(pi/4.0) -> h
        qasm_lines.append(f'h qm{qm}[0];')
        qasm_lines.append(f'rz(0.7853981633974483) qm{qm}[0];')  # pi/4
        qasm_lines.append(f'h qm{qm}[0];')
    qasm_lines.append('')
    
    # 使用具体的数值 - p 门，只对第一个模式的第一个量子比特应用
    qasm_lines.append(f'p(0.39269908169872414) qm0[0];')  # pi/8
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_shors_circuit_qasm(name, num_qubits, num_modes, cutoff, N=15, m=5, R=10, a=2, delta=1.0):
    """生成 Shor 算法电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    r = 0.222
    num_qubits_per_mode = math.ceil(math.log2(cutoff))
    
    # 使用 p 门，对前两个模式的所有量子比特应用
    for qubit_offset in range(num_qubits_per_mode):
        qasm_lines.append(f'p({r}) qm0[{qubit_offset}];')
        qasm_lines.append(f'p({r}) qm1[{qubit_offset}];')
    qasm_lines.append('')
    
    # 使用 p 门，对第三个模式的所有量子比特应用
    for qubit_offset in range(num_qubits_per_mode):
        qasm_lines.append(f'p({-math.log(delta)}) qm2[{qubit_offset}];')
    qasm_lines.append('')
    
    for i in range(R):
        # 使用 p 门，对第一个模式的所有量子比特应用
        for qubit_offset in range(num_qubits_per_mode):
            qasm_lines.append(f'p(1.0) qm0[{qubit_offset}];')
    qasm_lines.append('')
    
    for i in range(N):
        # 使用 p 门，对第二个模式的所有量子比特应用
        for qubit_offset in range(num_qubits_per_mode):
            qasm_lines.append(f'p(1.0) qm1[{qubit_offset}];')
    qasm_lines.append('')
    
    for i in range(m):
        # 对第二个和第三个模式的所有量子比特应用 CNOT
        for qubit_offset in range(num_qubits_per_mode):
            qasm_lines.append(f'cx qm1[{qubit_offset}],qm2[{qubit_offset}];')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_state_transfer_CVtoDV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val=0.29):
    """生成 CV 到 DV 状态转移电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    num_qubits_per_mode = math.ceil(math.log2(cutoff))
    for j in range(1, num_qubits + 1):
        for q_idx in range(num_qubits):
            # rx(pi/4) 等价于：h -> rz(pi/4) -> h
            qasm_lines.append(f'h q[{q_idx}];')
            qasm_lines.append(f'rz(0.7853981633974483) q[{q_idx}];')  # pi/4
            qasm_lines.append(f'h q[{q_idx}];')
        qasm_lines.append('')
        
        # 对每个模式的所有量子比特应用位移
        for qm in range(num_modes):
            # 使用 p 门
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'p({lambda_val}) qm{qm}[{qubit_offset}];')
        qasm_lines.append('')
        
        for q_idx in range(num_qubits):
            qasm_lines.append(f'rz(0.7853981633974483) q[{q_idx}];')  # pi/4
        qasm_lines.append('')
        
        # 对每个模式的所有量子比特应用位移
        for qm in range(num_modes):
            # 使用 p 门
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'p({lambda_val}) qm{qm}[{qubit_offset}];')
        qasm_lines.append('')
    
    for i in range(num_qubits):
        qasm_lines.append(f'h q[{i}];')
        if i == num_qubits - 1:
            # rx(pi) 等价于：h -> rz(pi) -> h
            qasm_lines.append(f'h q[{i}];')
            qasm_lines.append(f'rz(3.141592653589793) q[{i}];')  # pi
            qasm_lines.append(f'h q[{i}];')
            qasm_lines.append(f'p(3.141592653589793) q[{i}];')  # pi
        elif i == 0:
            qasm_lines.append(f'p(3.141592653589793) q[{i}];')  # pi
        else:
            # rx(pi) 等价于：h -> rz(pi) -> h
            qasm_lines.append(f'h q[{i}];')
            qasm_lines.append(f'rz(3.141592653589793) q[{i}];')  # pi
            qasm_lines.append(f'h q[{i}];')
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def create_state_transfer_DVtoCV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val=0.29):
    """生成 DV 到 CV 状态转移电路的 QASM 代码"""
    qasm_lines = []
    
    # 添加头部
    qasm_lines.append('// Generated by BQSim QASM generator')
    qasm_lines.append('')
    qasm_lines.append('OPENQASM 2.0;')
    qasm_lines.append('include "qelib1.inc";')
    qasm_lines.append('')
    
    # 添加量子寄存器
    for i in range(num_modes):
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        qasm_lines.append(f'qreg qm{i}[{num_qubits_per_mode}];')
    qasm_lines.append(f'qreg q[{num_qubits}];')
    qasm_lines.append('')
    
    # 生成电路操作
    for i in range(num_qubits):
        if i == num_qubits - 1:
            qasm_lines.append(f'p(3.141592653589793) q[{i}];')  # pi
            # rx(pi) 等价于：h -> rz(pi) -> h
            qasm_lines.append(f'h q[{i}];')
            qasm_lines.append(f'rz(3.141592653589793) q[{i}];')  # pi
            qasm_lines.append(f'h q[{i}];')
            qasm_lines.append(f'h q[{i}];')
        elif i == 0:
            qasm_lines.append(f'p(3.141592653589793) q[{i}];')  # pi
            qasm_lines.append(f'h q[{i}];')
        else:
            # rx(pi) 等价于：h -> rz(pi) -> h
            qasm_lines.append(f'h q[{i}];')
            qasm_lines.append(f'rz(3.141592653589793) q[{i}];')  # pi
            qasm_lines.append(f'h q[{i}];')
            qasm_lines.append(f'h q[{i}];')
        qasm_lines.append('')
    
    for j in range(num_qubits, 0, -1):
        # 对每个模式的所有量子比特应用位移
        num_qubits_per_mode = math.ceil(math.log2(cutoff))
        for qm in range(num_modes):
            # 使用 p 门
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'p({-lambda_val}) qm{qm}[{qubit_offset}];')
        qasm_lines.append('')
        
        for q_idx in range(num_qubits):
            qasm_lines.append(f'rz(-0.7853981633974483) q[{q_idx}];')  # -pi/4
        qasm_lines.append('')
        
        # 对每个模式的所有量子比特应用位移
        for qm in range(num_modes):
            # 使用 p 门
            for qubit_offset in range(num_qubits_per_mode):
                qasm_lines.append(f'p({-lambda_val}) qm{qm}[{qubit_offset}];')
        qasm_lines.append('')
        
        for q_idx in range(num_qubits):
            # rx(-pi/4) 等价于：h -> rz(-pi/4) -> h
            qasm_lines.append(f'h q[{q_idx}];')
            qasm_lines.append(f'rz(-0.7853981633974483) q[{q_idx}];')  # -pi/4
            qasm_lines.append(f'h q[{q_idx}];')
        qasm_lines.append('')
    
    qasm_lines.append('')  # 添加空行确保文件末尾有换行符
    return '\n'.join(qasm_lines)


def write_qasm_file(qasm_code, filename):
    """将 QASM 代码写入文件"""
    try:
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        with open(filename, 'w') as f:
            f.write(qasm_code)
        return True
    except Exception as e:
        print(f"Error writing QASM file: {e}")
        return False


def process_case(case):
    """处理单个 case，返回 (status, output_name, file_size_or_error)"""
    name = case['name']
    workload = case['workload']
    cutoff = case.get('cutoff', 4)
    num_qubits = case.get('num_qubits', 1)
    num_modes = case.get('num_modes', 1)
    
    output_name = f"{name}.qasm"
    output_path = os.path.join(OUTPUT_DIR, output_name)
    
    if os.path.exists(output_path):
        file_size = os.path.getsize(output_path)
        return ('skip', output_name, file_size)
    

    try:
        if workload == 'vqe_circuit':
            layers = case.get('layers', 2)
            qasm_code = create_vqe_circuit_qasm(name, num_qubits, num_modes, cutoff, layers)
        elif workload == 'jch_simulation_circuit':
            timesteps = case.get('timesteps', 5)
            qasm_code = create_jch_circuit_qasm(name, num_qubits, num_modes, cutoff, timesteps)
        elif workload == 'cat_state_circuit':
            alpha = case.get('alpha', 1.0)
            qasm_code = create_cat_state_circuit_qasm(name, num_qubits, num_modes, cutoff, alpha)
        elif workload == 'gkp_state_circuit':
            N_rounds = case.get('N_rounds', 9)
            r = case.get('r', 0.222)
            qasm_code = create_gkp_state_circuit_qasm(name, num_qubits, num_modes, cutoff, N_rounds, r)
        elif workload == 'qaoa_circuit':
            layers = case.get('layers', 2)
            s = case.get('s', 0.5)
            a = case.get('a', 1.0)
            qasm_code = create_qaoa_circuit_qasm(name, num_qubits, num_modes, cutoff, layers, s, a)
        elif workload == 'qft_circuit':
            n = case.get('n', 2)
            a = case.get('a', 1)
            append = case.get('append', 1)
            delta = case.get('delta', 0.1)
            qasm_code = create_qft_circuit_qasm(name, num_qubits, num_modes, cutoff, n, a, append, delta)
        elif workload == 'shors_circuit':
            N = case.get('N', 15)
            m = case.get('m', 5)
            R = case.get('R', 10)
            a = case.get('a', 2)
            delta = case.get('delta', 1.0)
            qasm_code = create_shors_circuit_qasm(name, num_qubits, num_modes, cutoff, N, m, R, a, delta)
        elif workload == 'state_transfer_CVtoDV_circuit':
            lambda_val = case.get('lambda', 0.29)
            qasm_code = create_state_transfer_CVtoDV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val)
        elif workload == 'state_transfer_DVtoCV_circuit':
            lambda_val = case.get('lambda', 0.29)
            qasm_code = create_state_transfer_DVtoCV_circuit_qasm(name, num_qubits, num_modes, cutoff, lambda_val)
        else:
            return ('unknown', output_name, workload)
        
        result = write_qasm_file(qasm_code, output_path)
        if result:
            file_size = os.path.getsize(output_path)
            return ('ok', output_name, file_size)
        else:
            return ('error', output_name, 'write failed')
            
    except Exception as e:
        return ('error', output_name, str(e))


def main():
    json_path = os.path.join(os.path.dirname(__file__), '../BQSim-main/sc26_scaling.json')
    
    if not os.path.exists(json_path):
        print(f"Cannot find sc26_scaling.json: {json_path}")
        return 1
    
    with open(json_path, 'r') as f:
        data = json.load(f)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    cases_by_cutoff = {}
    for case in data['cases']:
        cutoff = case.get('cutoff', 4)
        if cutoff not in ALLOWED_CUTOFFS:
            continue
        if cutoff not in cases_by_cutoff:
            cases_by_cutoff[cutoff] = []
        cases_by_cutoff[cutoff].append(case)
    
    sorted_cutoffs = sorted(cases_by_cutoff.keys())
    
    print(f"Found {len(data['cases'])} test cases in sc26_scaling.json")
    print(f"Generating QASM for cutoffs: {sorted_cutoffs}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Using {MAX_WORKERS} parallel workers")
    print("=" * 80)
    
    total_generated = 0
    total_skipped = 0
    errors = []
    
    for cutoff in sorted_cutoffs:
        print(f"\n>>> Processing cutoff = {cutoff}")
        print("-" * 80)
        
        cases = cases_by_cutoff[cutoff]
        
        with concurrent.futures.ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
            future_to_case = {executor.submit(process_case, case): case for case in cases}
            
            for future in concurrent.futures.as_completed(future_to_case):
                status, output_name, info = future.result()
                
                if status == 'skip':
                    print(f"[SKIP] {output_name} (already exists, {info} bytes)")
                    total_skipped += 1
                elif status == 'ok':
                    print(f"[OK] {output_name} ({info} bytes)")
                    total_generated += 1
                elif status == 'unknown':
                    print(f"[SKIP] {output_name} (unknown workload: {info})")
                else:
                    print(f"[ERROR] {output_name}: {info}")
                    errors.append(output_name)
    
    print("\n" + "=" * 80)
    print(f"Total QASM files generated: {total_generated}")
    print(f"Total skipped (already exist): {total_skipped}")
    if errors:
        print(f"Errors ({len(errors)}):")
        for e in errors:
            print(f"  - {e}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
